using System.ComponentModel.DataAnnotations;

namespace rest_api_blueprint.Models.Authentication.Google
{
    public class GoogleGrantResponse
    {
        [Required]
        public string Code { get; set; }

        /// <summary>
        /// Is generated by us to validate the request.
        /// </summary>
        [Required]
        public string State { get; set; }
    }
}
